---
- hosts: kube-workers
  become: true
  become_method: sudo
  roles:
  - shutdown
  tags:
  - workers

- hosts: kube-master
  become: true
  become_method: sudo
  roles:
  - shutdown
  tags:
  - master
