---
- name: "Reboot slave nodes"
  hosts: kube-workers
  become: true
  become_method: sudo
  roles:
  - reboot

- name: "Reboot master node"
  hosts: kube-master
  become: true
  become_method: sudo
  roles:
  - reboot
