---
- name: "Reboot slave nodes"
  hosts: kube-workers
  become: true
  become_method: sudo
  tasks:
  - name: "Reboot after 2 minutes"
    command: shutdown -r +2 "Server reboot initiated in 120 seconds"

- name: "Reboot master node"
  hosts: kube-master
  become: true
  become_method: sudo
  tasks:
  - name: "Reboot after 2 minutes"
    command: shutdown -r +2 "Server reboot initiated in 120 seconds"
