---
- hosts: localhost
  roles:
  - scaleup/verify

- hosts: kube-master
  become: true
  become_method: sudo
  roles:
  - kubeadm-token/get-valid-token

- hosts: kube-master
  roles:
  - set-fact-master-address

- hosts: "{{ TARGET_NODE }}"
  become: true
  become_method: sudo
  roles:
  - init-cluster/worker
