---
- hosts: localhost
  roles:
  - scaledown/verify
  tags:
  - always

- hosts: kube-master
  roles:
  - scaledown/master
  tags:
  - master

- hosts: "{{ TARGET_NODE }}"
  become: true
  become_method: sudo
  roles:
  - scaledown/worker
  tags:
  - workers
