---
- hosts: localhost
  roles:
  - scaleup/verify

- hosts: kube-master
  become: true
  become_method: sudo
  roles:
  - kubeadm-token/get-valid-token
  tags:
  - master

- hosts: kube-master
  roles:
  - set-fact-master-address
  tags:
  - master

- hosts: "{{ TARGET_NODE }}"
  become: true
  become_method: sudo
  roles:
  - install-kube
  - init-cluster/worker
  tags:
  - workers
