---
- name: "Initialize kubeadm on master"
  hosts: jarvis-kube-master
  become: true
  become_method: sudo
  tasks:
  - name: "Generate a token"
    command: kubeadm token generate
    register: kube_join_token
  - name: "Register master ip address."
    set_fact:
      master_ip_address: "{{ ansible_eth0.ipv4.address }}"
  - name: "Initialize kube adm"
    command: kubeadm init --token {{ kube_join_token.stdout }} --pod-network-cidr 10.244.0.0/16

- name: "All workers join master as slave nodes."
  hosts: jarvis-kube-workers
  become: true
  become_method: sudo
  vars:
    kube_join_token: "{{ hostvars['jarvis']['kube_join_token'].stdout }}"
    master_ip_address: "{{ hostvars['jarvis']['master_ip_address'] }}"
  tasks:
  - name: "Join master node with the generated token."
    command: kubeadm join --token={{ kube_join_token }} {{ master_ip_address }}
