---
- name: "Deploy load balancer"
  hosts: jarvis-kube-master
  vars:
    deployment_src_path: "{{ ansible_env.HOME }}/loadbalancer"
  pre_tasks:
  - fail:
      msg: "Loadbalancer node is not defined"
    when: loadbalancer_node is not defined
  tasks:
  - name: "Ensure directory exists"
    file:
      path: "{{ deployment_src_path }}"
      state: directory
  - name: "Copy deployment requirements"
    copy:
      src: "{{ item }}"
      dest: "{{ deployment_src_path }}"
      force: yes
    with_fileglob:
      - "../../essentials/kube-system/loadbalancer/deployment/*-deployment.yaml"
  - name: "Label loadbalancer node"
    command: kubectl label node {{ loadbalancer_node }} nginx-controller=traefik --overwrite
  - name: "Create deployment object"
    command: kubectl create -f {{ deployment_src_path }}/traefik-deployment.yaml
  - name: "Cleanup files"
    file:
      path: "{{ deployment_src_path }}"
      state: absent
