---
- fail:
    msg: Ingress controller node is not defined
  when: ingress_controller_node is not defined

- fail:
    msg: Ingress controller node must be a valid node in kube-workers group
  when: ingress_controller_node not in groups['kube-workers']

- name: Set directory name to copy files on remote
  set_fact:
    target_remote_dir: "{{ ansible_env.HOME }}/traefik/"

- name: Create target directory
  file:
    path: "{{ target_remote_dir }}"
    state: directory

- name: Label loadbalancer node
  command: kubectl label node {{ ingress_controller_node }} nginx-controller=traefik --overwrite

- name: Copy deployment configuration file
  copy:
    src: "{{ item }}"
    dest: "{{ target_remote_dir }}/"
    force: yes
  with_items:
    - "traefik-deployment.yaml"
    - "traefik-rbac.yaml"

- name: Create deployment
  command: kubectl apply -f "{{ item }}"
  with_items:
    - "{{ target_remote_dir }}/traefik-deployment.yaml"
    - "{{ target_remote_dir }}/traefik-rbac.yaml"
