apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jarvis-orchestrator
  namespace: jarvis-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: jarvis-orchestrator
    spec:
      containers:
      - name: jarvis-orchestrator
        image: lahsivjar/jarvis-orchestrator:latest
        env:
        - name: REDIS_HOST
          value: 'config-db.jarvis-system.svc.cluster.local'
        - name: REDIS_PORT
          value: '6379'
        ports:
        - containerPort: 8080
