apiVersion: v1
kind: Service
metadata:
  name: jarvis-orchestrator
  namespace: jarvis-system
spec:
  selector:
    run: jarvis-orchestrator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
