---
- name: Get a valid join token from kubeadm
  become: true
  become_method: sudo
  shell: kubeadm token list | awk '{ print $1 }' | tail -1
  register: join_token
- name: Register kubernetes join token for all worker nodes
  set_fact:
    kube_join_token: "{{ join_token.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['kube-workers'] }}"
