---
- name: "Initialize flannel for every host"
  hosts: jarvis-kube-master
  tasks:
  - name: "Copy config map to workers"
    copy:
      src: "../../essentials/kube-system/flannel/deployment/kube-flannel-configmap.yaml"
      dest: "{{ ansible_env.HOME }}/."
      force: yes
  - name: "Copy daemon set to workers"
    copy:
      src: "../../essentials/kube-system/flannel/deployment/kube-flannel-daemonset.yaml"
      dest: "{{ ansible_env.HOME }}/."
      force: yes
  - name: "Create config map object"
    command: kubectl create -f {{ ansible_env.HOME }}/kube-flannel-configmap.yaml
  - name: "Create daemon set object"
    command: kubectl create -f {{ ansible_env.HOME }}/kube-flannel-daemonset.yaml
  - name: "Cleanup files"
    file:
      path: "{{ ansible_env.HOME }}/kube-flannel-configmap.yaml"
      state: absent
  - name: "Cleanup files"
    file:
      path: "{{ ansible_env.HOME }}/kube-flannel-daemonset.yaml"
      state: absent
