---
- name: "Shutdown slave nodes"
  hosts: jarvis-kube-workers
  become: true
  become_method: sudo
  tasks:
  - name: "Halt after 1 minute"
    command: shutdown -h +1 "Server shutdown initiated, will shutdown in 60 seconds"

- name: "Shutdown master node"
  hosts: jarvis-kube-master
  become: true
  become_method: sudo
  tasks:
  - name: "Halt after 1 minute"
    command: shutdown -h +1 "Server shutdown initiated, will shutdown in 60 seconds"
