apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: py-helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: py-helloworld
    spec:
      containers:
      - name: jarvis-kube-py-helloworld
        image: lahsivjar/jarvis-kube-py-helloworld:latest
        ports:
        - containerPort: 8080
