apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: py-helloworld
spec:
  rules:
  - http:
      paths:
      - path: /py/helloworld
        backend:
          serviceName: py-helloworld
          servicePort: 8080
