---
- name: Join master node with the generated token.
  command: kubeadm join \
    --token={{ kube_join_token }} \
    --discovery-token-ca-cert-hash={{ ca_cert_hash }} \
    {{ master_apiserver_address }}
