---
- fail:
    msg: "TARGET_NODE variable is undefined, it must be passed to indicate the node name to shutdown"
  when: TARGET_NODE is undefined
- fail:
    msg: "A new node must be added in kube-workers group in hosts file and passed as TARGET_NODE"
  when: TARGET_NODE not in groups['kube-workers']
