---
- name: "Reset kube for workers"
  hosts: jarvis-kube-workers
  become: true
  become_method: sudo
  tasks:
  - name: "Reset kubeadm for workers"
    command: kubeadm reset

- name: "Reset kube for master"
  hosts: jarvis-kube-master
  become: true
  become_method: sudo
  tasks:
  - name: "Reset kubeadm for master"
    command: kubeadm reset
